apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argo
  source:
    repoURL: https://github.com/argoproj/argo-rollouts
    targetRevision: v1.1.1
    path: manifests/cluster-install
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true